.TH Athena\-VM 1 "06 January 22"
.SH NAME
athena\-vm \- Athena emulator
.SH SYNOPSIS
.B athena\-vm
[ \fB\-j\fR | \fB\-\-jit\fR ]
[ \fB\-b\fR \fIBOARD\fR | \fB\-\-board\fR \fIBOARD\fR]
.IR rom.bin
.SH DESCRIPTION
.B athena-vm
emulate Athena processor and athena based boards.
.SH FLAGS
.TP
.BR \-j ", " \-\-jit
Activate jit.
.TP
.BR \-\-dump\-asm
.TP
.BR \-h ", " \-\-help
Show help menu
.TP
.BR \-v ", " \-\-version
Show program version
.SH OPTIONS
.TP
.BR \-b ", " \-\-board =\fIBOARD\fR
Set the current board to emulate.
Default: miniathena
.TP
.BR \-\-dump\-regs =[\fInormal\fR|\fIpretty\fR]
.SH BUGS
There is no bug.

